# CI de Nivel 01 - disparo manual a partir de 1 clique

#nome do nosso 'pipeline'
name: 'Execução Manual'

#regras de disparo (gatilhos/triggers)
#gatilho de exec manual = workflow_disapatch

on:
  workflow_dispatch:

# trabalhos/trefas dentro do pipeline = jobs
jobs:
  e2e-tests:

  #maquina que o job vai executar
  runs-on: ubuntu-latest

  #passo do script de build
  steps:
    #clone do projeto
    - uses: actions/checkout@v4

    #instalacao do node
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x

    #instalacao do yarn
    - name: Instalando Yarn
      run: npm install -g yarn

    #instacao das dependencias
    - name: Inatalando dependencias
      run: yarn

      # instalacao do playwright
    - name: Instalando Playwright
      run: yarn run e2e