# CI de Nivel 01 - disparo dos testes dentro do pipe dev

#nome do nosso 'pipeline'
name: 'Execução Integrada'

#regras de disparo (gatilhos/triggers)
#gatilho de exec a partir de outro pipe = workflow_run

on:
  workflow_dispatch:

# trabalhos/trefas dentro do pipeline = jobs
jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Checando padronizacao do codigo
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Executando testes de unidade
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Executando testes E2e
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report

  deploy:
    runs-on: ubuntu-latest
    needs: [e2e-tests]

    steps:
      - name: Simulacao do Deploy
        run: echo "simulando deploy com sucesso"
